---
foreman:
  type: "object"
  required: true
  patternProperties:
      "^\\w+":
        "$ref": "#/properties/connections"
  additionalProperties: false

connections:
  type: "object"
  properties:
    server:
      type: string
      description: "IP/Hostname of the server"
      required: true
    username:
      type: string
      description: "Username to login to the server"
      required: true
    password:
      type: string
      description: "Password to login to the server"
      required: true
      secret: true
    
auto_remediate:
  type: "object"
  properties:
    last_checkin:
      type: "object"
      description: "Time frame for last checkin"
      required: false
      properties:
        date:
          type: string
          description: "Date of last response"
          required: true
        time:
          type: string
          description: "Time of the day"
          required: true
  additionalProperties: false
