---
foreman:
  type: object
  required: true
  patternProperties:
      "^\\w+":
        "$ref": "#/properties/connections"
  additionalProperties: false

connections:
  type: object
  properties:
    server:
      type: string
      description: "IP/Hostname of the server"
      required: true
    username:
      type: string
      description: "Username to login to the server"
      required: true
    password:
      type: string
      description: "Password to login to the server"
      required: true
      secret: true
  additionalProperties: false

query:
  type: object
  required: true
  properties:
    days:
      type: string
      description: "Days since last response"
      required: true
